### ISSUE TITLE
"trouble from intdy" error

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2#10]
I'm trying nlmixr2 on a current model, and I see the following error many times.  I can't share the data, but I wonder if there is an obvious issue that I'm missing:

```
intdy -- t = 2015.08 illegal. t not in interval tcur - _rxC(hu) to tcur
unhandled error message: EE:[lsoda] trouble from intdy, itask = 1, tout = 2015.08
 @(lsoda.c:820)×Ô
```

FYI, it repeats thousands of times.

**Comment by mattfidler** [comment]
You can simulate the estimates to see if it is a stable model.  This will make the FAQ, See #9 .

Another option is to simulate from the model, since that is now allowed too 😄 .  Of course change the inital estimates and make sure it is a published model

**Comment by billdenney** [comment]
This spurs me to think of a new "estimation method" (`est` argument): "HELP!" where it would do a detailed data check and report any data errors, run a simulation to let you know what the average ratio of PRED/DV is to show if there is something off, and maybe give a plot of the PRED/DV by time in some way that may be considered useful.

That's not really a feature request, but maybe it is how we suggest working with models when you have errors in the FAQ.

**Comment by billdenney** [comment]
When I just tried to simulate from my model and data, I got the below errors.  I'm digging deeper to try to figure out what is the matter:

```
> mod_sim <- nlmixr(object=one_cmt, data=d_mod, est="simulation")
Error : nlmixr2 estimation 'simulation' not supported
 can be one of 'fo', 'foce', 'focei', 'foi', 'nlme', 'posthoc', 'predict', 'rxSolve', 'saem', 'simulate'
Error: nlmixr2 estimation 'simulation' not supported
 can be one of 'fo', 'foce', 'focei', 'foi', 'nlme', 'posthoc', 'predict', 'rxSolve', 'saem', 'simulate'
> mod_sim <- nlmixr(object=one_cmt, data=d_mod, est="rxSolve")
Error in `$<-.rxSolve`(`*tmp*`, "reset", value = TRUE) : 
  Cannot convert object to an environment: [type=NULL; target=ENVSXP].
```

**Comment by billdenney** [comment]
For the message, is it possible to either suppress the unprintable ASCII or make it readable (after "lsoda.c:820")?

**Comment by billdenney** [comment]
FYI, the model itself seems stable.  When I simulated from the data (using `rxSolve(model, data)`), the DV/PRED figure went through the middle of the data, and it is a pretty simple one-compartment model with an adjustment for different PK assays.  I'm still looking...

**Comment by mattfidler** [comment]
A method for plotting this may be nice.

**Comment by mattfidler** [comment]
> For the message, is it possible to either suppress the unprintable ASCII or make it readable (after "lsoda.c:820")?

Anything is possible.  I have tried multiple times to suppress, but haven't managed yet.

**Comment by billdenney** [comment]
I believe that this is resolved now.
