### ISSUE TITLE
Issue in multiple endpoints scenario

### ISSUE THREAD

**Issue by diabloyg** [nlmixr2/nlmixr2#100]
Hi, it seemed that, even only the cmt is used with options(rxode2.combine.dvid=FALSE), the order of endpoints in model section should follow those in dataset, or it may go wrong. 

For example, in my dataset cb is the primary endpoint and cp is the secondary, and cb appears first after dosing record. 
![image](https://user-images.githubusercontent.com/52405097/211699173-819d535c-dae3-492c-9b83-5ce090518971.png)

However, if I write cp ahead of cb in the model, they are mismatched:
![image](https://user-images.githubusercontent.com/52405097/211699348-7d49af32-7229-4649-bc1b-6810142be30c.png)

Obviously the obs 3.5 and 10.5 were for cb instead of cp in the dataset. However, they have been exchanged, and the model results are obviously influenced due to such exchange. 

The issue was resolved after putting cb first in the model:
![image](https://user-images.githubusercontent.com/52405097/211699900-b8539ddc-d749-4173-afcb-590983d56588.png)

**Comment by mattfidler** [comment]
Can you simulate from your model and provide the code to reproduce this?

Thanks in advance.

**Comment by diabloyg** [comment]
Sorry I tried to simulate and reproduce this but it did not work. It seemed that the issue lies elsewhere :(

**Comment by mattfidler** [comment]
Perhaps if you can provide an anonymized data (only include the columns you need), you could reproduce:

This means:
- change the DV to nonsense information,
- change the doses (if needed)
- change the model names (if needed)
- change the model parameter estimates

If you can reproduce that with this dummy dataset, maybe we can figure out what is going on.

**Comment by mattfidler** [comment]
I will assume you have figured this out.
