### ISSUE TITLE
Error in function - incorrect number of arguments

### ISSUE THREAD

**Issue by pg320** [nlmixr2/nlmixr2#133]
I am trying to run a model which I previously had working on nlmixr2. After installing the latest version, it has stopped working now. 

I tried the example from the nlmixr2 website, but I get the following error:

```
library(nlmixr2)

## The basic model consiss of an ini block that has initial estimates
one.compartment <- function() {
  ini({
    tka <- 0.45 # Log Ka
    tcl <- 1 # Log Cl
    tv <- 3.45    # Log V
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0.1
    add.sd <- 0.7
  })
  # and a model block with the error sppecification and model specification
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    d/dt(depot) = -ka * depot
    d/dt(center) = ka * depot - cl / v * center
    cp = center / v
    cp ~ add(add.sd)
  })
}

## The fit is performed by the function nlmixr/nlmix2 specifying the model, data and estimate
fit <- nlmixr2(one.compartment, theo_sd,  est="saem", saemControl(print=0))
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00 
#> 
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
print(fit)
```

> Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
>   arguments imply differing number of rows: 1, 0
> Error: arguments imply differing number of rows: 1, 0

Could you help me resolve this?

**Comment by mattfidler** [comment]
Yes, you can either wait for CRAN to approve `nlmixr2est` or use the r-universe development version:

```r
install.packages(c("nlmixr2est"),
                 repos = c('https://nlmixr2.r-universe.dev',
                           'https://cloud.r-project.org'))
```

As of right now, we have been waiting for 2 days, so hopefully it will go through soon

![image](https://user-images.githubusercontent.com/514778/228866724-dbaebe0b-512d-4ce9-81a4-8b29393ebb51.png)

**Comment by mattfidler** [comment]
Hi @snailittle 

This is likely because the binaries have not been updated for every architecture on CRAN. Currently binaries are available for Windows (not Mac), but probably isn't on every mirror.

You should have `nlmixr2est` 2.1.4 for the functions to work correctly.

**Comment by mattfidler** [comment]
I believe this is fixed for most systems.
