### ISSUE TITLE
Cheatsheet link is broken

### ISSUE THREAD

**Issue by jeroenes** [nlmixr2/nlmixr2#14]
Thanks for releasing the new version of nlmixr, I am curious! 

Small thingy: clicking on the cheatsheet from the GitHub.ik menu resulted in a 404. 
https://github.com/nlmixr2/nlmixr2/raw/master/CheatSheet_nlmixr.pdf is the expected target. 

Jeroen

**Comment by mattfidler** [comment]
Thanks, fixed.  Should be correct when pkgdown is rebuilt.
