### ISSUE TITLE
Missing Values Error while there is no missing value in the data

### ISSUE THREAD

**Issue by chansgary** [nlmixr2/nlmixr2#153]
Dear Dr.Fidler and all nlmixr2 Users,

I really appreciate your help if this can be answered in a time manner. 

I had troubling building my model with the covariate effect, which I followed the exact steps from the tutorial on the official website. Here are my model fit and sample data, where the error: "column 'WT70' has only 'NA' values for id 'X'" keep repeating. When I tried to incoporate more covariates, same issue pops out.

I wonder if you could tell me if there is anything I should do about my data or model.

Here are the R codes and original data file:
```
library(readxl)
library(nlmixr2)
sampleData = read_excel("/sampleData.xls") 

mod.1CMT.wtcl <- function() {
  ini({
    tVc = log(c(1, 28, 50)) # log(V) (L)
    tCl = log(c(0.1, 10, 30)) #  log(Cl) (L/HR)
    wteff = fix(0.75) # log(WT/70) on CL
    eta.Vc ~ 0.5
    eta.Cl ~ 0.5
    add.sd <- 0.2 # Additive Error
    prop.sd <- 0.2 # Proportional Error
  })
  model({
    Vc = exp(tVc + eta.Vc)
    Cl <- exp(tCl + eta.Cl + wteff*log(WT70)) # lWT=log(WT70)
    linCmt() ~ add(add.sd) + prop(prop.sd)
  })
}

nlmixr2(mod.1CMT.wtcl)

fit.1CMT.wtcl.sampleData = nlmixr2(mod.1CMT.wtcl,sampleData,"focei") 

fit.1CMT.wtcl.sampleData$runInfo
```

[question.pdf](https://github.com/nlmixr2/nlmixr2/files/11523758/question.pdf)
[sampleData.xls](https://github.com/nlmixr2/nlmixr2/files/11523759/sampleData.xls)

**Comment by chansgary** [comment]
The following issues keep repeating:
## [1] "column 'WT70' has only 'NA' values for id '2'"
## [2] "column 'WT70' has only 'NA' values for id '1'"

**Comment by mattfidler** [comment]
This is likely a known issue, when time-varying covariates are in a specific format there is this false positive.

It has been fixed here:

https://github.com/nlmixr2/rxode2parse/pull/47

**Comment by mattfidler** [comment]
I will push this to `CRAN` on the next release. 

Since we have released recently we will wait to add this to CRAN until they ask us to update the `rxode2parse` package  or some more time passes (they have a policy about releasing too frequently).

**Comment by mattfidler** [comment]
> > This is likely a known issue, when time-varying covariates are in a specific format there is this false positive.
> > It has been fixed here:
> > [nlmixr2/rxode2parse#47](https://github.com/nlmixr2/rxode2parse/pull/47)
> 
> HI Dr. Fidler, Thank you for your reply. I also wonder this variable might not be time-varying. Since `WT70` in my case is the fixed weight for each id. However, the warning messages are still there. Do you imply that it would be fixed in the next release of `rxode2`?

Well, I cannot say for sure because I do not have your data or your model and therefore cannot reproduce your issue.

However if you want to check (and back up your R installation first so you can reproduce whatever you have), you can install everything from the r-universe:

```r
install.packages(c("dparser", "nlmixr2data", "lotri", "rxode2ll",
                   "rxode2parse", "rxode2random", "rxode2et",
                   "rxode2", "nlmixr2est", "nlmixr2extra", "nlmixr2plot",
                   "nlmixr2"),
                 repos = c('https://nlmixr2.r-universe.dev',
                           'https://cloud.r-project.org'))
```

That matches the development versions and should tell you right away if this version fixes the issue you have.
