### ISSUE TITLE
Simplify .Rbuildignore to ignore all vignettes?

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2#175]
PR #174 is not completing because the vignette is not ignored in the .Rbuildignore file.  Looking at the file, it is ignoring all of the vignettes one-by-one.  Should we simplify the .Rbuildignore file to ignore the entire vignettes directory rather than each vignette one-by-one?

**Comment by mattfidler** [comment]
Thats fine with me for now
