### ISSUE TITLE
Installing nlmixr2 on CodeOcean

### ISSUE THREAD

**Issue by zackpm** [nlmixr2/nlmixr2#182]
Hi all,

Running into problems installing nlmixr2 on CodeOcean (I'm new to CodeOcean) which is the preferred computational solution for my company. Having a hard time deciphering the error(s) during installation, but I've included a snippit below:

```
[ERROR MESSAGE]
<stdin>:1:10: fatal error: hb-ft.h: No such file or directory
compilation terminated.

ERROR: configuration failed for package ‘textshaping’
* removing ‘/usr/local/lib/R/site-library/textshaping’
* installing *source* package ‘symengine’ ...
** package ‘symengine’ successfully unpacked and MD5 sums checked
** using staged installation
====== configuring symengine R package ======
== current working directory
/tmp/RtmpIp0ZEv/R.INSTALL99a5fc517f9/symengine
== /bin/bash
== cmake:
cmake is not in PATH, try looking for /Applications/CMake.app/Contents/bin/cmake
cmake can not be found
ERROR: configuration failed for package ‘symengine’
* removing ‘/usr/local/lib/R/site-library/symengine’
cat: ragg.out: No such file or directory
cat: pkgdown.out: No such file or directory
cat: devtools.out: No such file or directory
cat: nlmixr2est.out: No such file or directory
cat: nlmixr2extra.out: No such file or directory
cat: nlmixr2plot.out: No such file or directory
cat: nlmixr2.out: No such file or directory
Warning in install.packages :
  installation of one or more packages failed,
  probably ‘textshaping’, ‘symengine’, ‘ragg’, ‘pkgdown’, ‘devtools’, ‘nlmixr2est’, ‘nlmixr2extra’, ‘nlmixr2plot’, ‘nlmixr2’
```

**Comment by mattfidler** [comment]
Hi @zackpm 

It seems that you are having problems installing `symengine`.  If `CodeOcean` is a linux variant, you need to install system dependencies to install symengine.  See:

https://github.com/symengine/symengine.R#installation

**Comment by mattfidler** [comment]
Also  it seems that you cannot install `textshaping`.  According to CRAN you also need the following binaries installed: 

- freetype2
- harfbuzz
- fribidi

I'm unsure who you would need to talk to to have these dependencies installed.



</body>
</html>

**Comment by zackpm** [comment]
I appreciate the quick response @mattfidler - I will contact my internal IT people about getting these dependencies installed and follow up here with a potential resolution.

**Comment by mattfidler** [comment]
Great!

Good luck
