### ISSUE TITLE
Residual error model restriction

### ISSUE THREAD

**Issue by charlottemt** [nlmixr2/nlmixr2#206]
Hi,

I have a PKPD model in nlmixr. My PD output is on a percentage scale and would like to have a residual error model with a 0-100 restriction. 

I would be grateful for any direction on this.
Thank you!

**Comment by mattfidler** [comment]
Sure.

You probably  want `pd ~ logitNorm(logit.sd, 0, 100)` or maybe `pd ~ probitNorm(probit.sd, 0, 100)`

**Comment by mattfidler** [comment]
There are many endpoint distributions possible. The residual functions are documented here:

https://nlmixr2.github.io/rxode2/articles/rxode2-syntax.html#residual-functions-when-using-rxode2-functions

**Comment by charlottemt** [comment]
Many thanks @mattfidler.
