### ISSUE TITLE
Generation of the negative CPRED data

### ISSUE THREAD

**Issue by ckcho0625** [nlmixr2/nlmixr2#210]
Dear Fidler and nlmixr2 users

I have a one question for the generated CPRED data 

I am currently building a population pharmacokinetic model using nlmixr2. Unexpected results have been observed, where CPRED values are predicted as negative, resulting in a goodness-of-fit plot that shows a negative slope. Despite testing various models, some CPRED values and slope of DV vs. CPRED have consistently been predicted as negative.  The generated CPRED data is quite different to the generated PRED data. When I tested the model with other data I have, normal results (positive DV vs. CPRED slope) were observed. I would like to inquire whether there might be an issue with the plasma concentration data I have. I wonder how can I solve this problem. I attached the code and the goodness-of-fit profiles.

Kind regards

![124d4d55-e1b7-411c-9ff8-6391c3578240](https://github.com/nlmixr2/nlmixr2/assets/63388711/3c73c68a-673a-47b8-aa8c-087c8d8defc1)

![9e419cb9-3e20-4509-90ad-ce48f92fb5f1](https://github.com/nlmixr2/nlmixr2/assets/63388711/79abff86-a3bd-465e-8848-4b540e2df339)

Model code
  practice <- function() {
    ini({
      TCL <- log(2944.2); label("CL")       # 2944.2: calculated CL/F of NCA (L/h)
      TV  <- log(7833.5); label("V")         # 7833.5: calculated Vz/F of NCA (L)
      TKA <- log(0.5); label("Ka")     

      Eta.CL + Eta.V ~ c(1.0, 1.0, 1)
      Eta.KA ~ 1.0
      prop.err <- 1.0
    })
    model({
      CL <-  exp(TCL+Eta.CL)
      V  <- exp(TV+Eta.V)
      KA <- exp(TKA+Eta.KA)
      d/dt(depot) = -KA*(depot)
      d/dt(cent) = KA*(depot)-CL/V*(cent)
      Cp = cent/V
      Cp ~ prop(prop.err)
    })
  }

nlme_practice <- nlmixr2(practice, PKdata, "saem", table=tableControl(cwres=T,npde = T))
print(nlme_practice)

**Comment by mattfidler** [comment]
One other thing to keep in mind is you are using `saem` which is not the focei approximation.  The solution that you have may violate the assumptions of the focei approximation since the `saem` estimation routine does not use it.

**Comment by mattfidler** [comment]
This seems like more of a disucssion so I am moving it to the discussions so it will be easier for others to find in the future.
