### ISSUE TITLE
ERROR: dependency 'Rcpp' is not available for package 'RcppArmadillo' 

### ISSUE THREAD

**Issue by nholford** [nlmixr2/nlmixr2#229]
I have attempted to install nlmixr2 on a new laptop. I've installed rtools42 (rtools42-5355-5357) and R 4.2.2 and tried to install the nlmixr2 package using from the Rgui with:
install.packages("nlmixr2",dependencies = TRUE)
When asked if I wanted to install source code for compilation I responded with "Yes".
The installation process ended with
ERROR: dependency 'Rcpp' is not available for package 'RcppArmadillo' 
I cannot find any help online to explain why I get this error message so I am asking here to see if someone can suggest what needs to be done.

**Comment by billdenney** [comment]
My first guess is that there is a version requirement for Rcpp.  Would it be reasonable to try with the current version of R and Rtools?

It may be possible with R 4.2, but that may take more work.

**Comment by nholford** [comment]
Bill - thanks for this suggestion to update the R version.  Rik Schoemaker suggested I use R-4.3.3. That, along with Rtools43 worked to install nlmixr2.

I wsa naively followign the installation instructions on https://nlmixr2.org/ which indicated I should R 4.2.x and Rtools42. Perhaps it time for someone to update the installation instructions?

**Comment by billdenney** [comment]
It looks like our integration to create nlmixr2.org is not working.  I'm trying to fix that in #230.

**Comment by mattfidler** [comment]
Updated install instructionsd.
