### ISSUE TITLE
Documentation: Expand documentation for installation

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2#23]
I think that it would help users to take them from a new computer to installation of nlmixr2 in an instruction documentation.

Most users come from a background where they will have R installed, but at least some will come with a computer with nothing.  Also, getting the tool-chain setup correctly can be a stumbling block for some users.  While there is lots of documentation out there of how to do these things, helping users find it would be useful.

The reason I'm writing this is because I wanted to look up the best way to install R on my new Linux system.  I have it automated for other systems, but I had to look at my own instructions to ensure that I got it right.

I would assume that there would be three main sections (Linux, Windows, and Mac) and within each main section, there could be flavors (Linux distribution, Windows version, Mac version/processor type).  Ideally, where feasible, we could also have a shell script/batch file to help along the way.

**Comment by mattfidler** [comment]
There is something in rxode2.  I like DRY in documentation and need to
figure out a way to share documentation between the projects.  Maybe a
submodule....
