### ISSUE TITLE
Documentation Request: nlmixr2 objects

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/nlmixr2#24]
In depth look at nlmixr2 output objects

**Comment by john-harrold** [comment]
So I think I'll create a csv file that will contain the fields in the nlmixr2 object and the corresponding description. Where should that csv file go? Which package and directory location?

**Comment by mattfidler** [comment]
Probably in this page.  In `rxode2`, I have it in a vignette with a `DT` `data.table` output:

https://cran.wustl.edu/web/packages/rxode2/vignettes/rxode2-syntax.html

I actually used a template so I could use the same text in multiple places; The vignette and the rxode2 documentation too.

https://github.com/nlmixr2/rxode2/blob/308ebba8c535bfa9c6f0171b770afc6d263996e0/R/rxode2.R#L109

Something like this could be helpful.  But, nlmixr2 is actually in the `nlmixr2est` package.

**Comment by john-harrold** [comment]
Sorry if I'm being daft here, but are you saying I should add it to that vignette in rxode2. It just seems strange to put the nlmixr2 object description in rxode2. Or are you saying I should create a similar vignettes in nlmixr2?

**Comment by mattfidler** [comment]
Similar vignettes in nlmixr2

**Comment by john-harrold** [comment]
I added it to nlmixr2est since that's where the nlmixr function is located/documented:

https://github.com/nlmixr2/nlmixr2est/pull/351
