### ISSUE TITLE
Is nlmixr2Test necessary?

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2#26]
Can we rework the tests and remove the nlmixr2Test() function?  Specifically, I think that it does what is now done with `testthat::skip_on_cran()` and `testthat::skip_on_ci()` and those would likely make it easier for others to create and review tests..

**Comment by mattfidler** [comment]
Sure.

Note that this was done to deal with Travis limitations and had environment variables run different levels of testing.  

If we remove it we would have to reinvent it if something similar happens in the future.

For me, I am perfectly OK with removing nlmixr2Test

**Comment by billdenney** [comment]
I think that current testthat's `skip_if()` is probably generalizable enough to do whatever we want (e.g. look for environmental variables).  I'll take a look at this in a few days.

**Comment by mattfidler** [comment]
Before committing, please keep in mind that `testthat` has repeatedly failed `RxODE` and still reports a successful testing suite.  I haven't had time to track it down, but... perhaps it would be fixed by testthat3.

**Comment by billdenney** [comment]
Can you point me to an example of what you mean about failing `RxODE`?  My experience with testthat is that it has been simple and generally foolproof, so I'd like to watch out for issues that may pop up.

**Comment by mattfidler** [comment]
https://github.com/r-lib/testthat/issues/1358

**Comment by mattfidler** [comment]
It still fails with a minor issue that I haven't fixed.  Still reports it as a successful run.
