### ISSUE TITLE
vpcPlot time sampling

### ISSUE THREAD

**Issue by danieleboaretti** [nlmixr2/nlmixr2#263]
Hello,

I would like to know if it is possible to increase the time sampling of the simulations of the vpcPlot so that it is not limited to the observation times of the fit data. Eventually, in this way, the function can have an optional argument to plot the VP using all the extra time sampling points.

For example, the fit data might have observations at time 0, 24, 48 and at the moment the vpcPlot would return the VP with the data at those time points. In my question above one could have the option to simulate and plot the VP also in all the time points of a user-defined time interval like `seq(0,48)`

This could also apply to vpcSim, I guess they are related in the way the VP is created.

I hope this is feasible and that my question is clear. I can try to formulate it better if needed.

Thank you for your support

Daniele

**Comment by mattfidler** [comment]
Hi Daniele, 

This is currently not possible.  From a methodology perspective, a `vpc` only uses the data that is included, not add more data to it. 

Of course, you can use a nlmixr2 model to simulate from if you want to get a smoother curve.  

This sort of analysis is shown in the following page:

https://nlmixr2.org/articles/xgxr-nlmixr-ggpmx.html#simulation-of-a-new-scenario-with-rxode2

In this example, there are more time-points than what was originally in the dataset.  

I am unsure of what you are trying to do with more simulation points than what was observed by the data.  If you do that, I don't think the `vpc` package would handle it (or it would simply drop your extra simulated points...?)

Perhaps with more context, I can provide better help.

**Comment by danieleboaretti** [comment]
Thank you for that link. That link provided support for what I wanted in terms of the simulation, even if it requires some extra steps for integrating the observed data into the plots of the confidence interval and other specific vpc options like `stratify` that could apply also there. 
For now I will close this issue, thanks.

**Comment by mattfidler** [comment]
You can use `confint(..., by="")` for stratification (fyi).  

Perhaps someday you could extract the `augPred` generated data for simualtion in a new scenario,
