### ISSUE TITLE
Is there a method to output the SE of epsilon and omega like NONMEM?

### ISSUE THREAD

**Issue by Aki349** [nlmixr2/nlmixr2#274]
Hi,

I would like to obtain the SE values to calculate the confidence intervals of the parameters (epsilon, sigma) after estimation.
Is there a method to output these values?

Thank you

**Comment by mattfidler** [comment]
Not through a single estimation method at this time. You can get this information by bootstrapping though.

It is on the development backlog (meaning it is on our list of things to do)
