### ISSUE TITLE
focei-inner

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/nlmixr2#30]
Running test manually works, but testthat does not work.

**Comment by mattfidler** [comment]
@billdenney 

Taking out 

```
Config/testthat/parallel: true
```

From the description fixes this.  I am unsure what is happening here, but I think removing this is an OK option.

**Comment by mattfidler** [comment]
If you are familiar with debugging this, feel free to add it back simply running `testthat::test(filter="focei-inner")`

**Comment by billdenney** [comment]
I'll take a look.  It is probably something about test sequencing and a setting being changed in another test.

**Comment by mattfidler** [comment]
Thanks.

I think it is something else.  I cant get a printout of the error message
when it is running in parallel though.
