### ISSUE TITLE
Documentation: Remove the "A_" from compartment names in WBC model

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2#32]
In the following model, the "A_" at the beginning of compartment names caused some confusion during the nlmixr2 course at PAGE.  A trainee thought that the "A_" was required for setting initial conditions.  I think it would simplify the documentation clarity to remove the "A_" in this model.

https://github.com/nlmixr2/nlmixr2/blob/11e7b082939842bb34ff0b6729a2a4babe7a444c/vignettes/wbc.Rmd#L67-L79

**Comment by mattfidler** [comment]
Sounds fine to me if you are game
