### ISSUE TITLE
Why is there a stop() in the middle of wang2007 tests?

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2#38]
Should this `stop()` be changed to a `skip()`?

https://github.com/nlmixr2/nlmixr2/blob/11cb1fb214fcf8e7237e14e908bcf199cdfb7f8a/tests/testthat/test-focei-wang2007.R#L756

**Comment by mattfidler** [comment]
Because I am currently working through and expanding this test.  The stop
is where I got to..  You can replace it with a skip if you want
