### ISSUE TITLE
Convert output to a message to make it silent

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2#42]
As with rxode2, I'm trying to make successful testing in nlmixr2 silent when successful.  There are two outputs that are not silent with `suppressMessages(suppressWarnings(...))`.

```
calculating covariance matrix
done
```

I think that they come from the following two lines of code.  Can you please convert these to messages?

https://github.com/nlmixr2/nlmixr2/blob/11cb1fb214fcf8e7237e14e908bcf199cdfb7f8a/src/inner.cpp#L4928
https://github.com/nlmixr2/nlmixr2/blob/11cb1fb214fcf8e7237e14e908bcf199cdfb7f8a/src/inner.cpp#L6230

**Comment by mattfidler** [comment]
Perhaps I can convert it to be silent when running the inner problem and the suppress message environment is active, but I cannot convert it to a `message`.

**Comment by mattfidler** [comment]
(Note the items in `rxode2` are actually not `message`s either)

**Comment by billdenney** [comment]
It's low priority, overall.  But, I find it easier to find testing issues when successful testing is silent.  So, whenever I can make things silent, I really want to.

**Comment by mattfidler** [comment]
Should be fixed
