### ISSUE TITLE
Suggests needed for vignettes

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2#6]
The following packages are needed for the vignettes:

* broom.mixed
* dotwhisker
* dplyr
* flextable
* ggplot2
* ggPMX
* huxtable
* officer
* patchwork
* readr
* tidyr
* xgxr
* xpose
* xpose.nlmixr

We should take a look if the list can be simplified and if not, put them all in the `Suggests` field of the `DESCRIPTION` file.

Edit: added patchwork

**Comment by mattfidler** [comment]
I vote leaving them as is and not actually having vignettes for now. Simply
use them in the pkgdown website.  They will break cran time limits
otherwise.


What to you think?

**Comment by billdenney** [comment]
For now, that makes sense to me.

I think that people do find vignettes on CRAN (I definitely do, at least).  So, we should consider a way to make them somehow accessible.  Perhaps there is a very basic vignette with a simple example that is not run and then a pointer to the pkgdown website?

**Comment by mattfidler** [comment]
I was thinking of a good readme with pointers to the documentation.  That way it points the place to get more information

**Comment by mattfidler** [comment]
It also does not have to run on cran machines

**Comment by mattfidler** [comment]
The basic vignette I would wish to include is running nlmixr, though `xpose.nlmixr` should support `nlmixr` for that to work
