### ISSUE TITLE
Memory issue with very large data sets

### ISSUE THREAD

**Issue by RikSchoemaker** [nlmixr2/nlmixr2#63]
Running an analysis with 1500 patients and many thousands of dosing records, I get the following error message after succesful convergence when calculating residuals/tables:

Error in .calcCwres0(fit, data, thetaEtaParameters, table, dv = dv, predOnly,  : 
  Mat::init(): requested size is too large; suggest to enable ARMA_64BIT_WORD
Error: Mat::init(): requested size is too large; suggest to enable ARMA_64BIT_WORD

Would it be an option to enable ARMA_64BIT_WORD in RcppArmadillo?

Kind regards,

Rik

**Comment by mattfidler** [comment]
Thanks @RikSchoemaker 

Simply adding the flag has the package stop compiling:

https://github.com/nlmixr2/nlmixr2est/pull/277

I am definitely looking at it. Unfortunately, it ins't as simple as I thought it might be.

**Comment by mattfidler** [comment]
From the armadillo manual

> Use 64 bit integers. Automatically enabled when using a 64-bit platform, except when using Armadillo in the R environment
(via RcppArmadillo). Useful if matrices/vectors capable of holding more than 4 billion elements are required. This can also be
enabled by adding #define ARMA_64BIT_WORD before each instance of #include <armadillo>

I don't think 64 bit integers are supported in R.  Perhaps an option to drop cwres or maybe some debugging build to figure out where it is making such a large matrix/vector

**Comment by mattfidler** [comment]
You could try turning of `npde`.  I am unsure if you can turn off cwres...

**Comment by mattfidler** [comment]
The development version of nlmixr2est now has `ARMA_64BIT_WORD` turned on.  You can check if it fixes your problem
