### ISSUE TITLE
Issue for the fitting question

### ISSUE THREAD

**Issue by jerryjenq** [nlmixr2/nlmixr2#64]
Hi Dear author,
I am a student who met a problem fitting the one compartment system
<img width="792" alt="截圖 2022-11-03 下午3 52 15" src="https://user-images.githubusercontent.com/117395105/199820695-84568c64-9fb4-47cc-8627-85dd3e5fcde3.png">
How can I fix this problem? I have downloaded the newest GCC and gfortran and I find a way to fix this question online. Is that the correct way to fix it?

**Comment by billdenney** [comment]
@jerryjenq, sorry for the delay on this.  It appears that you do not have gfortran installed in a way that nlmixr2 can find it.

Did you install everything as described here: https://github.com/nlmixr2/nlmixr2#mac-compilation-tools-setup
