### ISSUE TITLE
Bootstrap for the Same method

### ISSUE THREAD

**Issue by miriamkhayam** [nlmixr2/nlmixr2#81]
Hello I am Miss Miriam I work for my thesis project on nlmixr2 and more particularly on bootstrap .
I noticed that the BootstrapFit function works only for the Focei method and even in the site there is only one example for the Focei method .
My question is does the bootstrap work for the Saem method too or is it not available?

Miriam K.

**Comment by mattfidler** [comment]
Hi @miriamkhayam 

It works for whatever method you use.  If you use `saem` for estimation, it will use `saem` for boostrapping.

I just tested on the `theo_sd` example and it runs `saem` for the bootstrap.

**Comment by mattfidler** [comment]
If you have a reproducible example where it isn't work, please let me know.
