### ISSUE TITLE
Add stable release dates for reproducing results?

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/nlmixr2#84]
Ie when to install from mran to get results that you may have used in the past.

**Comment by billdenney** [comment]
Isn't that already covered by the releases page, https://github.com/nlmixr2/nlmixr2/releases?

**Comment by mattfidler** [comment]
Well, the `nlmixr2` releases doesn't reflect that the `nlmixr2est` was updated due to CRAN issues until it got to a CRAN-based stable release of `2.1.3`, so to me this doesn't show the progression, but it may not matter.

**Comment by billdenney** [comment]
True, but the next step for that is to point to each of those release pages.  If there's a simple way to automatically extract those dates, then sure.  Otherwise, it seems like a moderate amount of work to keep up with all the package release dates whenever anything is released.

**Comment by billdenney** [comment]
Something like this may be able to automate it: https://stackoverflow.com/questions/37367649/determine-number-of-versions-in-history-of-r-package-on-cran

**Comment by mattfidler** [comment]
Hm.  Perhaps it isn't necessary.  Too much work on each release, I guess
