### ISSUE TITLE
MRAN is retiring potential impact on installing nlmixr2 for R < 4.2

### ISSUE THREAD

**Issue by john-harrold** [nlmixr2/nlmixr2#98]
I saw this recently:

https://mastodon.social/@jladata@fosstodon.org/109647239415435765

It looks like MRAN is retiring in the near future. I only mention it because it's currently required to get a version of symengine installed that works with R 4.0.1 and 4.1.x. 

From reading it seems RStudio provides a similar service of providing packages at a particular point in time.

**Comment by mattfidler** [comment]
Rewrote by installing a specific version, that way we don't even have to depend on the rstudio mirror (though there is little risk here I think).
